# Este arquivo contem os parametros de input para executar os testes.

title = "Benchmark Datasets"

[info]
dataset_link = "https://people.sc.fsu.edu/~jburkardt/datasets/knapsack_01/knapsack_01.html"

[datasets]

    [datasets.one]
    description = "A set of 10 weights and profits for a knapsack of capacity 165."
    capacity = 165
    weights_objects = [ 23, 31, 29, 44, 53, 38, 63, 85, 89, 82 ]
    profits_objects  = [ 92, 57, 49, 68, 60, 43, 67, 84, 87, 72 ]
    optimal_selection_weights = [ 1, 1, 1, 1, 0, 1, 0, 0, 0, 0 ]

    [datasets.two]
    description = "A set of 5 weights and profits for a knapsack of capacity 26."
    capacity = 26
    weights_objects = [ 12, 7, 11, 8, 9 ]
    profits_objects  = [ 24, 13, 23, 15, 16 ]
    optimal_selection_weights = [ 0, 1, 1, 1, 0 ]

    [datasets.three]
    description = "A set of 6 weights and profits for a knapsack of capacity 190."
    capacity = 190
    weights_objects = [ 56, 59, 80, 64, 75, 17 ]
    profits_objects  = [ 50, 50, 64, 46, 50, 5 ]
    optimal_selection_weights = [ 1, 1, 0, 0, 1, 0 ]

    [datasets.four]
    description = "A set of 7 weights and profits for a knapsack of capacity 50."
    capacity = 50
    weights_objects = [ 31, 10, 20, 19, 4, 3, 6 ]
    profits_objects  = [ 70, 20, 39, 37, 7, 5, 10 ]
    optimal_selection_weights = [ 1, 0, 0, 1, 0, 0, 0 ]

    [datasets.five]
    description = "A set of 8 weights and profits for a knapsack of capacity 104."
    capacity = 104
    weights_objects = [ 25, 35, 45, 5, 25, 3, 2, 2 ]
    profits_objects  = [ 350, 400, 450, 20, 70, 8, 5, 5 ]
    optimal_selection_weights = [ 1, 0, 1, 1, 1, 0, 1, 1 ]

    [datasets.six]
    description = "A set of 7 weights and profits for a knapsack of capacity 170. The knapsack can be packed to an optimal weight of 169."
    capacity = 170
    weights_objects = [ 41, 50, 49, 59, 55, 57, 60 ]
    profits_objects  = [ 442, 525, 511, 593, 546, 564, 617 ]
    optimal_selection_weights = [ 0, 1, 0, 1, 0, 0, 1 ]

    [datasets.seven]
    description = "A set of 15 weights and profits for a knapsack of capacity 750, from Kreher and Stinson, with an optimal profit of 1458."
    capacity = 750
    weights_objects = [ 70, 73, 77, 80, 82, 87, 90, 94, 98, 106, 110, 113, 115, 118, 120 ]    
    profits_objects  = [ 135, 139, 149, 150, 156, 163, 173, 184, 192, 201, 210, 214, 221, 229, 240 ]
    optimal_selection_weights = [ 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1 ]

    [datasets.eight]
    description = "A  set of 24 weights and profits for a knapsack of capacity 6404180, from Kreher and Stinson, with an optimal profit of 13549094."
    capacity = 6404180
    weights_objects = [ 382745, 799601, 909247, 729069, 467902, 44328, 34610, 698150, 823460, 903959, 853665, 551830, 610856, 670702, 488960, 951111, 323046, 446298, 931161, 31385, 496951, 264724, 224916, 169684]
    profits_objects  = [ 825594, 1677009, 1676628, 1523970, 943972, 97426, 69666, 1296457, 1679693, 1902996, 1844992, 1049289, 1252836, 1319836, 953277, 2067538, 675367, 853655, 1826027, 65731, 901489, 577243, 466257, 369261 ]
    optimal_selection_weights = [ 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1 ]



